trigger:
  batch: true
  branches:
    include:
    - '*'

jobs:

- job: 'Test'
  strategy:
    matrix:
     Python36Linux:
       imageName: 'ubuntu-16.04'
       python.version: '3.6'
     Python36Windows:
       imageName: 'vs2017-win2016'
       python.version: '3.6'
     Python36Mac:
       imageName: 'macos-10.14'
       python.version: '3.6'
     Python37Linux:
       imageName: 'ubuntu-16.04'
       python.version: '3.7'
     Python37Windows:
       imageName: 'vs2017-win2016'
       python.version: '3.7'
     Python37Mac:
       imageName: 'macos-10.14'
       python.version: '3.7'
     Python38Linux:
       imageName: 'ubuntu-16.04'
       python.version: '3.8'
     Python38Windows:
       imageName: 'vs2017-win2016'
       python.version: '3.8'
     Python38Mac:
       imageName: 'macos-10.14'
       python.version: '3.8'
     Python39Linux:
       imageName: 'ubuntu-16.04'
       python.version: '3.9'
     Python39Windows:
       imageName: 'vs2017-win2016'
       python.version: '3.9'
     Python39Mac:
       imageName: 'macos-10.14'
       python.version: '3.9'
    maxParallel: 4
  pool:
    vmImage: $(imageName)

  steps:
  - template: .azure/steps.yml

- job: 'Test_self_hosted'
  strategy:
    matrix:
     Python36LinuxARM64:
       imageName: 'macmini-debian'
       python.version: '3.6'
       architecture: 'ARM64'
     Python37LinuxARM64:
       imageName: 'macmini-debian'
       python.version: '3.7'
       architecture: 'ARM64'
     Python38LinuxARM64:
       imageName: 'macmini-debian'
       python.version: '3.8'
       architecture: 'ARM64'
     Python39LinuxARM64:
       imageName: 'macmini-debian'
       python.version: '3.9'
       architecture: 'ARM64'
  pool:
    name: "Default"

  steps:
  - template: .azure/steps.yml
    parameters:
      python.version: $(python.version)
      architecture: $(architecture)
