trigger:
  batch: true
  branches:
    include:
    - '*'

jobs:

#- job: 'Tests1'
#  strategy:
#    matrix:
#      Python36Linux:
#        imageName: 'ubuntu-16.04'
#        python.version: '3.6'
#      Python36Windows:
#        imageName: 'vs2017-win2016'
#        python.version: '3.6'
#      Python36Mac:
#        imageName: 'macos-10.14'
#        python.version: '3.6'
#      Python37Linux:
#        imageName: 'ubuntu-16.04'
#        python.version: '3.7'
#      Python37Windows:
#        imageName: 'vs2017-win2016'
#        python.version: '3.7'
#      Python37Mac:
#        imageName: 'macos-10.14'
#        python.version: '3.7'
#      Python38Linux:
#        imageName: 'ubuntu-16.04'
#        python.version: '3.8'
#      Python38Windows:
#        imageName: 'vs2017-win2016'
#        python.version: '3.8'
#      Python38Mac:
#        imageName: 'macos-10.14'
#        python.version: '3.8'
#      Python39Linux:
#        imageName: 'ubuntu-16.04'
#        python.version: '3.9'
#      Python39Windows:
#        imageName: 'vs2017-win2016'
#        python.version: '3.9'
#      Python39Mac:
#        imageName: 'macos-10.14'
#        python.version: '3.9'
#    maxParallel: 4
#  pool:
#    vmImage: $(imageName)
#
#  steps:
#  - template: .azure/steps.yml
#    parameters:
#      python_version: '$(python.version)'
#      architecture: 'x64'
#
#- job: 'Tests2'
#  strategy:
#    matrix:
#      Python36LinuxARM64:
#        python.version: '3.6'
#      Python37LinuxARM64:
#        python.version: '3.7'
#      Python38LinuxARM64:
#        python.version: '3.8'
#      Python39LinuxARM64:
#        python.version: '3.9'
#  pool:
#    name: "Default"
#
#  steps:
#  - template: .azure/steps.yml
#    parameters:
#      python_version: '$(python.version)'
#      architecture: 'ARM64'

- job: 'Tests3'
  strategy:
    matrix:
      Python39MacARM64:
        python.version: '3.9'
  pool:
    name: "Default"

  steps:
  - template: .azure/steps.yml
    parameters:
      python_version: '$(python.version)'
      architecture: 'X64'
